import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const { name, shared } = context.query;

//   const isShared = shared !== undefined;

//   // return the properties so they are available in the `Index` component
//   return {
//     props: {
//       name: decodeURI(name as string),
//       isShared,
//     },
//   };
// };

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hello world</h1>
      </main>

      <footer>
        <span>copyright Tyler Nevell 2021</span>
      </footer>
    </div>
  );
};

export default Home;
