import type { NextPage } from 'next';
import Head from 'next/head';

// export const getStaticProps: GetStaticProps = async () => {
//   const menuItems = await fetch(ROUTE.PAGE).then((r) => r.json());
//   if (!menuItems) {
//     return {
//       notFound: true,
//     };
//   }

//   return {
//     props: {
//       data: {
//         menuItems,
//       },
//     },
//   };
// };

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tyler Nevell: Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hello world</h1>
      </main>

      <footer>
        <span>copyright Tyler Nevell 2021</span>
      </footer>
    </div>
  );
};

export default Home;
